### PR TITLE
Who is who page

### PR DESCRIPTION
**Pull request by markknol**
I updated the who is who page, added some data and some missing images.

I did it directly in this branch and merged the staging into it, hope you don't mind.

It looks like this:
whoiswho

closes https://github.com/HaxeFoundation/haxe.org/issues/96

### CODE REVIEW

**Comment by ibilon** [comment]
Looks good :+1:

**Comment by markknol** [comment]
@Simn can this be merged?

**Comment by Simn** [comment]
Yeah, thanks! Looks *slightly* better than the one we made...

**Comment by Simn** [comment]
By the way, can you deal with the menu centering so we can merge staging into master soon?

**Comment by Simn** [comment]
Oh and also @markknol, you should definitely be on that Who is Who page as well!

**Pull request merged**
