### PR TITLE
Update highlighter library

### PR DESCRIPTION
**Pull request by tobil4sk**
Update the highlighter library so we can finally stop depending on an ancient version of nodejs.

See: https://github.com/ibilon/Highlighter/pull/5

### CODE REVIEW

**Comment by tobil4sk** [comment]
Hm, just tested it and highlighting is a bit broken now :sweat_smile:...
image

**Comment by tobil4sk** [comment]
A bit better now, but something odd is happening with `if` `while` and possibly other keywords:
Before:
image

Now:
image

**Comment by tobil4sk** [comment]
Ok, I got it now, it looks like I had messed up the order of theme settings when themes have parent themes.
image

**Comment by kLabz** [comment]
Would need to merge https://github.com/ibilon/Highlighter/pull/5 first and update install path here :)

Other than that, it seems ok (I didn't test the website locally yet, though)
What's the added `vscode-oniguruma` dependency for?

**Comment by tobil4sk** [comment]
> What's the added vscode-oniguruma dependency for?

I think it has replaced `oniguruma` but it now has to be installed separately and vscode-textmate has to be pointed to use it:
https://github.com/microsoft/vscode-textmate?tab=readme-ov-file#using. I tried to get by without using it but it broke something.

**Comment by tobil4sk** [comment]
> Would need to merge https://github.com/ibilon/Highlighter/pull/5 first and update install path here :)

Done!

**Pull request merged**
