### PR TITLE
Editors and IDEs: link to the new VSCode extension, not legacy

### PR DESCRIPTION
**Pull request by Gama11**

### CODE REVIEW

**Comment by Gama11** [comment]
Is `master` right? I just noticed the default branch is `staging`.

**Comment by Simn** [comment]
Bah I always forget about that...

**Comment by Gama11** [comment]
I was linked to the `master` file from the "contribute to this page" link:

**Comment by Simn** [comment]
Pushed it to staging too.

**Comment by ibilon** [comment]
> I was linked to the master file from the "contribute to this page" link:

I'll fix that.

**Comment by ibilon** [comment]
@Simn how did you push it? Staging got a different commit than master (with the same content but git doesn't look at that)
fixed it

**Comment by Simn** [comment]
I cherry picked it off of master... is that bad?

**Comment by Gama11** [comment]
Well, it means the branches aren't "even", because cherry-picking creates a new commit. Looks like @ibilon merged the branches though?

**Comment by ibilon** [comment]
> because cherry-picking creates a new commit

Yeah, doing `git pull origin master --rebase` should be better, if that doesn't work there's always merge.

> Looks like @ibilon merged the branches though?

Merged it yes, commited and pushed back to master. So now they're the same.

**Comment by Simn** [comment]
I thought it was bad to rebase pushed branches too...

**Comment by ibilon** [comment]
It's not optimal, but merge commits look so bad.

**Pull request merged**
