### PR TITLE
Lossless image Optimization (250+ images)

### PR DESCRIPTION
**Pull request by FlipFloop**

### CODE REVIEW

**Comment by Aurel300** [comment]
Good, I assume that was `pngcrush` / `optipng` for the PNGs? For the SVGs, is it mostly just dropping the whitespace? Does the file still seem identical if you open it in InkScape?

**Comment by markknol** [comment]
If we want really small we could consider webp too, but that requires different image implementation, like this: 

```html
<picture> 
  <source data-srcset="img/image.webp" type="image/webp"/> 
  <img src="img/image.gif" loading="lazy"/>
</picture>
```

In combination with `loading="lazy"` it could lead in even less bandwidth in some cases.

**Comment by FlipFloop** [comment]
Actually, I only used lossless image compressors, here is the list:

- AdvPNG
- OxiPNG
- Zopfli

For the SVGs, I used SVGCleaner.

I haven't tried Inkscape but I've done many times and they all look the same!

**Comment by Aurel300** [comment]
Ok, if the SVGs ever cause trouble, we can roll those back. Thanks!

**Pull request merged**
