### PR TITLE
Add build instructions for FreeBSD

### PR DESCRIPTION
**Pull request by sexybiggetje**
Adds a simple instruction list to the page for compiling haxe from source on FreeBSD.

### CODE REVIEW

**Comment by Simn** [comment]
I'm not a Linux user, but doesn't step 2 miss a command?

**Comment by sexybiggetje** [comment]
It's not Linux, but you're still correct. Should have checked better when I updated the dependency list.
I've updated it in a subsequent commit to this patch. Cheers.

**Comment by Simn** [comment]
I see, thanks.

One other thing about the last line: Since you include information on how to git clone initially, it would be consistent to also mention the git command required to update. Right now it sounds like running `gmake haxe` would handle all the updating.

**Comment by sexybiggetje** [comment]
That's a valid point, I've updated the patch accordingly to include the git pull command.

**Comment by Simn** [comment]
Thanks!

**Comment by jasononeil** [comment]
Thanks for this!  I'm not a BSD user, I think this is the first time I've seen official instructions for Haxe on BSD. I'm sure there will be some grateful BSD users out there :)

**Comment by sexybiggetje** [comment]
For starters myself, hence my writeup ;). There is stoll a small issue with the ocamllibs project, for which I opened a ticket. Just a path that needs adjusting.

**Pull request merged**
