### PR TITLE
Starting a who is who page

### PR DESCRIPTION
**Pull request by ibilon**
See #96

### CODE REVIEW

**Comment by ibilon** [comment]
Needs to be finished before merging since I added it in the sitemap.

**Comment by Simn** [comment]
That's great, thanks!

I didn't realize it was that easy to add a new page, nice.

**Comment by Simn** [comment]
I have added you to the haxe.org team, can you push this to a branch so we can work on it more easily?

**Comment by ibilon** [comment]
Done, thanks.

**Comment by Simn** [comment]
Someone should figure out how to get things onto http://staging.haxe.org/

**Comment by ibilon** [comment]
With that commit https://github.com/HaxeFoundation/haxe.org/commit/7782d99a93f849deb11e0b0fcc2fbffa7e35d8dd it'll deploy the staging branch on it.

But I'm never 100% sure when I touch at travis' file.

**Comment by ncannasse** [comment]
BTW on the staging version there's some wrong spacing on the home page under the haxe logo

**Comment by ibilon** [comment]
Updated the staging branch with the latest commits, that fixed it.

Went ahead and made it the default branch so we can make commit more freely/safely and then merge on master when ready.

**Comment by Simn** [comment]
Good idea!

**Pull request closed without merging**
