### PR TITLE
Javascript does have the Sys API

### PR DESCRIPTION
**Pull request by dionjwa**

### CODE REVIEW

**Comment by ibilon** [comment]
No it does not, although with nodejs it can, the target itself doesn't support the sys api.

**Comment by ibilon** [comment]
I wonder if hxnodejs should have its own line though.

**Comment by ibilon** [comment]
Man I should learn to read, didn't see the last line of the diff.
Still unsure about saying javascript has sys api.

**Comment by nadako** [comment]
hxnodejs doesn't fully implement the sys api, since it's synchronous, and node.js is not, so we can't e.g. implement `Sys.stdout()` (without [hacks](https://github.com/HaxeFoundation/hxnodejs/issues/64) at least).

There are people [who think we shouldn't even claim that we support nodejs at all](https://groups.google.com/d/msg/haxelang/0ZVIbjXc1Wc/-Pmz8ED6BAAJ), so I wouldn't call haxe/nodejs a proper "sys" target yet.

See related hxnodejs issue: https://github.com/HaxeFoundation/hxnodejs/issues/59.

**Comment by ibilon** [comment]
Since hxnodejs doesn't support the full sys api let's not say it is a sys target.

**Pull request closed without merging**
