### PR TITLE
Target tier list

### LINKED ISSUE #407: Target tier list
I would like to document a target tier list which indicates how much focus we put on individual targets. My suggestion:

## Tier 1

Actively maintained by the core compiler team with a strong focus from the Haxe Foundation

* JavaScript
* HashLink
* Eval

## Tier 2

Maintained mostly by individuals in their free time

* C++
* JVM
* Lua
* PHP

## Tier 3

Kept up-to-date, but not much active development

* C#
* Java
* Python
* Flash
* Neko

## Tier 4

Essentially deprecated

* Actionscript 3

### PR DESCRIPTION
**Pull request by Aurel300**
Closes #407.

 - [x] add tiers and explain
 - [x] reorder targets strictly by "Since"
 - [x] link to "static target" part in the manual
 - [x] change PHP to PHP5 and add deprecation notice
 - [x] link to string encoding part in the manual
 - [ ] version compatibility table somehow
 - [ ] threading support? debugging support?

(WIP because I want to address #394 also.)

### CODE REVIEW

**Comment by RealyUniqueName** [comment]
I don't think threading or debugging supported are needed here.
What else do we need to finish this?

**Comment by RealyUniqueName** [comment]
Maybe sort targets by tier?

**Comment by Aurel300** [comment]
Sure, feel free to edit or suggest commits. The current sorting is in order of introduction, but that is probably not very useful. There were also suggestions to have fewer tiers. @Simn thoughts?

**Comment by ibilon** [comment]
There's only as3 in tier 4 and it's already been removed.

**Comment by Gama11** [comment]
Maybe Java is tier 4 at this point, or soon anyway?

**Comment by RealyUniqueName** [comment]
I'm going to merge this.
Does anybody want to add anything?

**Comment by Simn** [comment]
Yes

**Comment by Simn** [comment]
Done

I leave it up to you if you want to move PHP to tier 1. It would make sense to me because you're working for HF in official capacity.

**Pull request merged**
