### PR TITLE
Add PHP Page

### PR DESCRIPTION
**Pull request by robinrodricks**
Revision #2 of the PHP Page

- Removed Tink
- Specified local PHP server not required
- Fixed note on PHP platform API

### CODE REVIEW

**Comment by robinrodricks** [comment]
The travis build fails to generate some downloads so I guess that's nothing to do with my PR.

https://travis-ci.org/HaxeFoundation/haxe.org/jobs/505118677#L763

**Comment by robinrodricks** [comment]
@markknol @RealyUniqueName Can you check this please?

**Comment by markknol** [comment]
Thanks! Ill merge now, we can always do updates!

**Comment by robinrodricks** [comment]
Awesome! Could you explain a little bit why I need to create one branch per page? I've never worked with this model.

**Comment by markknol** [comment]
Good question;  I struggle a lot with git every now and then too but the idea is, you create a feature in a local branch, once it is complete, you do a pull request. Once it get merged, you remove that branch. And repeat that.

I think it is this workflow https://www.atlassian.com/git/tutorials/comparing-workflows/forking-workflow

**Comment by robinrodricks** [comment]
Okay,
That's doable.

>

**Pull request merged**
