### PR TITLE
added 075 & 082

### PR DESCRIPTION
**Pull request by lewislepton**

### CODE REVIEW

**Comment by Simn** [comment]
You somehow managed to create a PR with merge conflicts...

**Comment by lewislepton** [comment]
hmmm, really weird. il have a look. but thought it was fine. odd

must have been the news of GitHub being bought by Microsoft that done... yes, ill say its that ;)

but ill/ have a look-see in a bit

**Comment by lewislepton** [comment]
did try a minor bit of editing. but other than that, did not see anything that would break it

**Comment by Simn** [comment]
My guess is that you weren't on latest `staging` when you made your changes. Try rebasing again and resolve the conflicts.

**Pull request closed without merging**
