### PR TITLE
Add instructions for running unit tests.

### PR DESCRIPTION
**Pull request by georgkoester**
Shameless plug: Mentions the docker image created by me.

### CODE REVIEW

**Comment by Simn** [comment]
I didn't merge this because I'm not quite sure why it should be on the building Haxe page. I'm guessing that's a Linux thing...

**Comment by jasononeil** [comment]
Ah, my apologies.  I've just commited a clean up of the text anyway.  Do you recommend a different location or would you rather leave it somewhere else?

(Possible the README.md or a wiki page on the main Haxe repo?)

**Comment by Simn** [comment]
My bad for not commenting before. To be honest I'm not sure why this information is interesting at all for "casual Haxe builders".

**Comment by jasononeil** [comment]
I tend to agree.  I think it's good to have the information somewhere though, for people who want to contribute (and not waste Travis' time).  

Perhaps in the Github wiki, with a link from the README?  I feel like the people using the Github wiki are far more likely to be looking to contribute (as opposed to just get Haxe installed)

**Comment by Simn** [comment]
Yeah github wiki sounds like a good place.

**Pull request merged**
