### PR TITLE
Improve PHP Page

### PR DESCRIPTION
**Pull request by robinrodricks**
Add info on inline code & externs.

### CODE REVIEW

**Comment by robinrodricks** [comment]
@markknol is this fine?

**Comment by markknol** [comment]
Some notes:
- You are linking to https://api.haxe.org/v/development/php/Syntax.html#code that is development API docs. I wouldn't link to there because it might change. Which brings the issue that this is Haxe4-only thing soooo maybe lets keep it like this until Haxe 4 is actually released?
- "You can use third-party PHP libraries, for instance this code that uses.." Is this the best gist to demonstrate how to use libraries?

Btw you should remove your branch after it is merged, locally and the remote one. Then create new one based on staging. Now you keep committing in same branch. You should use this workflow to avoid conflicts. Hope that makes sense.

**Comment by robinrodricks** [comment]
To address your points:

- Done
- Yes, its the *only* gist I found

Ok, will do that for subsequent PRs.

**Comment by robinrodricks** [comment]
@markknol Could you accept this please? I'll create a new branch the next PR onwards if thats fine...

**Pull request closed without merging**
