### PR TITLE
High-Quality Haxe Logo ICO, made from the PNG file. 

### PR DESCRIPTION
**Pull request by Jens-G**
This is not intended to replace the favicon, but to provide a high-quality icon for other needs, where the web-optimized, rather low-quality favicon would not suffice.

### CODE REVIEW

**Comment by jasononeil** [comment]
I misread this when I merged.  You're providing a new icon, not a replacement for the old one.  Do you have a specific place you intend to load this?  Because presumably we'd need to update the templates etc.  

If not I might revert the merge.

**Comment by Simn** [comment]
I understood this as sort of "press kit material".

**Comment by jasononeil** [comment]
Oh, that's fine then.  So do I need to link to it from anywhere?

**Comment by Simn** [comment]
I don't think so, at least not right now. It's nice to have the URL though in case someone asks for it.

**Pull request merged**
