### PR TITLE
New navigation

### PR DESCRIPTION
**Pull request by markknol**
* added new navigation (part of https://github.com/HaxeFoundation/haxe.org/issues/105)
* added connect menu (closes https://github.com/HaxeFoundation/Project-Management/issues/34)
* removed community dropdown. We will lose http://haxe.org/community/community-support.html and http://haxe.org/community/jobs-and-services.html but I think they are not needed (anymore).
* moved blog to more prominent place in menu
* moved events page to foundation folder (can we use a redirect on the old page for this?)
* added divider support in the navigation/sitemap, because it looks nice

haxe-navigation

What do you think?

### CODE REVIEW

**Comment by Simn** [comment]
I think that... I'm gonna merge it immediately and ask questions later.

**Comment by nadako** [comment]
Wow, Mark's PRs are such pleasure to look at :)

**Comment by markknol** [comment]
Thanks, I believe after this navigation update, Haxe will immidiate go viral. ;)

**Comment by nadako** [comment]
I wouldn't be surprised! Anyway, a neat and maintained website adds a lot to credibility IMO, so great job on this!

**Comment by markknol** [comment]
Note to self: haxedevelop.org and haxe.io needs to be in this menu somewhere.

**Comment by Merelleya** [comment]
Ohhhh this is sooo shiny.

I have not smiled about a navigation that much ...ever!

Am 08/03/2016 um 00:37 schrieb Mark Knol:

**Comment by markknol** [comment]
Hey thanks I also put the blog in the connect menu everywhere. I think haxedevelop doesnt need to be in the menu, otherwise i dont know where. What abou haxe.io? We can put it in the connect too?

**Comment by ncannasse** [comment]
Two things I would like to see changed:

- is it normal that navigation is left aligned ? on big screens I prefer page alignement like current haxe.org (or github btw)

- search bar has disappeared

**Comment by ncannasse** [comment]
Great work BTW, sorry if I'm pointing only the negative, I love everything else :)

**Comment by markknol** [comment]
Thanks!

Yes, I found the searchbar quite distractive in the design. You can still search,but after clicking on the icon. Most modern browsers search stuff if you type something in the url bar and I think most of our users know this, so I'm not worried they will not find what they are searching for. 

About the alignment, good point. I can restrict it to a maximum width. Can you share an image of your screen, my resolution is not that high.

**Comment by ncannasse** [comment]
Ah, I didn't see the search because it was as the opposite of the screen. I guess using page width will make it more easy to find (not isolated in top right corner)

Here's the screen on original haxe.org
haxe_page

**Comment by markknol** [comment]
I can align the menu items in the center, but I will keep the search and logo to left/right side. This is because I want to have consistent looking navigation, and not all sites are center aligned (try.haxe/api.haxe).

**Comment by Simn** [comment]
I think it should still be left-aligned, but offset on the left like on api.haxe.org and lib.haxe.org.

What's your screen resolution?

**Pull request merged**
