### PR TITLE
Merge in the blog

### PR DESCRIPTION
**Pull request by jasononeil**
- You can preview it here: http://staging.haxe.org/blog/
- I think we should wait until there's at least 3 or 4 articles ready to go before we merge it in, so maybe it's smart to wait until everyone is back on board in the new year.
- Most of the actual code for the blog is being kept in a separate repo https://github.com/ufront/ufblog
- I **think** I've set this up so Travis will deploy it correctly when merged, but it's possible I've missed something.

### CODE REVIEW

**Comment by Simn** [comment]
Nice! I'm glad to see this is finally taking form.

**Comment by markknol** [comment]
Great! I think the landingspage of the blog should display an overview/excerpt of the articles, not the full content.

**Comment by Simn** [comment]
Does anyone feel responsible for this? I see that the PR doesn't merge anymore so it's going to require some work.

**Comment by andyli** [comment]
If you want to have the blog online now, I can look into merging this.

I wonder will @jasononeil come back anytime soon? Even if I can sort this out, the whole ufront stack still need a person to maintain.

**Comment by Simn** [comment]
Currently nobody knows, so I suppose we have to assume that we'll have to deal with it somehow.

**Comment by Simn** [comment]
Up!

**Comment by andyli** [comment]
Do you mean you want it merged and online now?

**Comment by Simn** [comment]
I've been wanting that for two months. I bring it up again now because HaxeDevelop would make a nice entry.

**Comment by andyli** [comment]
Alright, I saw that it was on hold for accumulating more blog posts before online.
I am going to work on it now.

**Comment by ncannasse** [comment]
It is not on hold, we want to have it online ASAP :)

**Comment by andyli** [comment]
It's live now!
I hope Jason has told you how to manage the user accounts and posts... I have little idea on those. And I don't have an account to log in its admin system : P

**Comment by Simn** [comment]
I "think" @Merelleya knows about that.

**Comment by markknol** [comment]
I cannot find it in the menu yet is that correct?

**Comment by Simn** [comment]
Yes, we have to sort some things out yet.

**Comment by ncannasse** [comment]
Thanks Andy, we would like to have only the first paragraph on http://haxe.org/blog so you can scroll between the posts without having to read them all (with of course a link "Read more...")

Also, we need to check how we gives access to this blog from the home page, but it's not the most important, since most traffic usually comes from social media sharing of blog posts which lands directly on post

**Comment by Simn** [comment]
It looks like there's already a template for the listing: https://github.com/HaxeFoundation/haxe.org/blob/master/www/view/article/list.html

**Comment by Simn** [comment]
I tried figuring out what's going on with these templates, but it doesn't make much sense to me. What appears on the blog looks like a combination of both templates (https://github.com/HaxeFoundation/haxe.org/blob/master/www/view/article/list.html and https://github.com/HaxeFoundation/haxe.org/blob/master/www/view/article/article.html), but I have no idea why it does that.

**Comment by Simn** [comment]
My theory is that your push to the whoiswho branch (https://github.com/HaxeFoundation/haxe.org/commit/41d73f0dcaa7f5493fe8cb93139cfa7848f9bfcc) got pulled to ssh://haxe.org/data/newhaxe/repo and then the changes to master would require a merge. That would also explain why my subsequent push to the whoiswho branch (https://github.com/HaxeFoundation/haxe.org/commit/1c234ad7f5a2575015c1ad0bd0e8cb7a1c7cc3ee) made it through travis (https://travis-ci.org/HaxeFoundation/haxe.org/builds/113458118) but nothing else currently does.

What I don't understand is why the whoiswho branch changes aren't showing on haxe.org.

**Comment by Simn** [comment]
Err, didn't mean to post that here... https://github.com/HaxeFoundation/haxe.org/commit/94d7244dffc412dd65129c66ad8e1d92cc02041e

**Pull request merged**
