### PR TITLE
Improvements for PHP page

### PR DESCRIPTION
**Pull request by robinrodricks**
Just some minor fixes. Hope my git history is not too messy.

### CODE REVIEW

**Comment by robinrodricks** [comment]
@markknol  is this fine?

**Comment by robinrodricks** [comment]
Travis is failing to generate downloads. Not an issue with my page.

https://travis-ci.org/HaxeFoundation/haxe.org/jobs/505665108#L762

**Comment by Gama11** [comment]
Aren't the commits squashed on merge anyway?

**Comment by ibilon** [comment]
I tend to use the rebase and merge to keep the individual commit history, but yeah it'd work with squash.

**Comment by Gama11** [comment]
I think the squash-merge option was pretty much created for cases like this. :)

**Pull request merged**
