### PR TITLE
Libraries

### PR DESCRIPTION
**Pull request by ConfidantCommunications**
May I suggest adding this page to the new site? It is an updated version of the old one at http://old.haxe.org/doc/libraries
I always thought it was pretty cool to see all these different tools summarized and I also found it to be a pretty handy reference which was better than the haxelib site. I'm willing to update it from time to time if you agree to the merge.

### CODE REVIEW

**Comment by ncannasse** [comment]
I would prefer if we have better ways to categorize libraries in haxelib website without having the library author to modify his package.json + resubmit (cc @jasononeil)

**Comment by ConfidantCommunications** [comment]
If we were to focus on using the haxelib site for this I would like to see the following:
* Support for items not available on haxelib, including software
* Easy community contribution in light of previous point 
* Support for categories with long names
* Avoid half-baked tag names such as "cross" 
* Better graphic design and interface (I might be able to contribute here)
* Easier to browse
* Ratings system so that dead projects would not overwhelm the popular, proven ones

What needs to happen for some of this to take place?

**Comment by ncannasse** [comment]
> What needs to happen for some of this to take place?
Wait a few more days :)

**Comment by ConfidantCommunications** [comment]
Obviously I'm late to the game. :)

**Comment by ConfidantCommunications** [comment]
My first commit may still be relevant (removal of deprecated page).

**Comment by Simn** [comment]
I have deleted the page by hand.

**Pull request closed without merging**
