### PR TITLE
Added branding page

### PR DESCRIPTION
**Pull request by markknol**
Added a branding page:
 * Logo downloads (as pngs, svg, pdf in some sizes and colors)
 * Branding colors reference table 

Fixes a new bit of https://github.com/HaxeFoundation/Project-Management/issues/26

### CODE REVIEW

**Comment by Simn** [comment]
Could you remove it from the menu first so we can have a look at it before it goes "live"?

**Comment by markknol** [comment]
done

**Comment by markknol** [comment]
What is needed to check it? Can it just be merged or something?

**Comment by Simn** [comment]
Yeah, we don't have a better solution at the moment.

**Comment by markknol** [comment]
http://haxe.org/foundation/branding.html

**Comment by ncannasse** [comment]
Ok for me

**Comment by markknol** [comment]
@Merelleya @Simn What do you think? If it's ok, ill add it to the menu too.

**Comment by Simn** [comment]
I don't have any objections.

**Comment by Merelleya** [comment]
This is cool! put it on!

**Pull request merged**
